### ISSUE TITLE
HTTP response code 400 (Bad request) 

### ISSUE THREAD

**Issue by AdTromp** [xebialabs-community/xlr-bamboo-plugin#4]
I have added a Bamboo server to the Shared Configuration. It's a valid url/username/Password combination. But the Test option gives a error:

Exception: HTTP response code 400 (Bad request) in <script> at line number 28

I can use this server nonetheless in a Bamboo task (RunPlan).

XLRelease 7.0.2
xlr-bamboo-plugin 1.0.2

**Comment by jdewinne** [comment]
This got fixed in commit [7a85347](https://github.com/xebialabs-community/xlr-bamboo-plugin/commit/7a85347eded2bdb1251c3b52ebba876787b5cb56). Can you try the latest version [v1.1.1](https://github.com/xebialabs-community/xlr-bamboo-plugin/releases/tag/v1.1.1)

**Comment by AdTromp** [comment]
I've installed version 1.1.1 and it works! Thanks.
