### ISSUE TITLE
This plugin doesn't follow the standard username, password pattern of other plugins

### ISSUE THREAD

**Issue by ksondere** [xebialabs-community/xlr-bamboo-plugin#5]
Every other plugin I use in xebialabs has a username and password override of shared settings.

This one does not.  So if I actually set the login as property for this plugin all of my other automated plugins fail because they don't use the same username.

Because of this, the plugin is currently unusable for our company.

**Comment by zvercodebender** [comment]
Resolved in release [v1.1.5](https://github.com/xebialabs-community/xlr-bamboo-plugin/releases/tag/v1.1.5)
